//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTMSV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcJournalConsignment
    {
        public int ID { get; set; }
        public Nullable<int> AcJournalID { get; set; }
        public Nullable<int> AcJournalDetailID { get; set; }
        public Nullable<int> InScanID { get; set; }
        public int AcHeadID { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
