//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTMSV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcOPInvoiceDetail
    {
        public int AcOPInvoiceDetailID { get; set; }
        public Nullable<int> AcOPInvoiceMasterID { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<System.DateTime> LastTransDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<bool> StatusClose { get; set; }
        public Nullable<int> AcMemoJournalID { get; set; }
        public Nullable<int> AcJournalID { get; set; }
    
        public virtual AcOPInvoiceMaster AcOPInvoiceMaster { get; set; }
    }
}
