//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTMSV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AWBStockDetail
    {
        public int AWBStockDetailID { get; set; }
        public int AWBStockID { get; set; }
        public string AWBNoFrom { get; set; }
        public string AWBNoTo { get; set; }
    }
}
