//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTMSV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AWBStatu
    {
        public int AWBStatusID { get; set; }
        public Nullable<int> StatusDescriptionID { get; set; }
        public string AWBNO { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> statusUpdationID { get; set; }
        public string Remarks { get; set; }
        public string FormID { get; set; }
        public string Status { get; set; }
        public Nullable<bool> statusUpdate { get; set; }
    }
}
