//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTMSV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AWBTrackStatu
    {
        public int AWBTrackStatusId { get; set; }
        public int InScanId { get; set; }
        public string AWBNo { get; set; }
        public System.DateTime EntryDate { get; set; }
        public int StatusTypeId { get; set; }
        public string ShipmentStatus { get; set; }
        public int CourierStatusId { get; set; }
        public string CourierStatus { get; set; }
        public int UserId { get; set; }
        public Nullable<int> ShipmentDetailID { get; set; }
    }
}
