//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTMSV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourierStatu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CourierStatu()
        {
            this.DRRConsignments = new HashSet<DRRConsignment>();
        }
    
        public int CourierStatusID { get; set; }
        public string CourierStatus { get; set; }
        public string StatusCourier { get; set; }
        public string StatusType { get; set; }
        public Nullable<int> StatusTypeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DRRConsignment> DRRConsignments { get; set; }
    }
}
