//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTMSV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerInvoiceDetail
    {
        public int CustomerInvoiceDetailID { get; set; }
        public int CustomerInvoiceID { get; set; }
        public int InScanID { get; set; }
        public string ConsignmentNo { get; set; }
        public Nullable<int> TaxPercentage { get; set; }
        public Nullable<decimal> FreightCharge { get; set; }
        public Nullable<decimal> DocCharge { get; set; }
        public Nullable<decimal> CustomsCharge { get; set; }
        public Nullable<decimal> OtherCharge { get; set; }
        public Nullable<int> RecPayStatus { get; set; }
        public Nullable<int> RecPayDetailId { get; set; }
        public Nullable<decimal> NetValue { get; set; }
    
        public virtual CustomerInvoice CustomerInvoice { get; set; }
    }
}
