//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTMSV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DebitNote
    {
        public int DebitNoteID { get; set; }
        public string DebitNoteNo { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> AcJournalID { get; set; }
        public Nullable<int> customerID { get; set; }
        public Nullable<int> FyearID { get; set; }
        public Nullable<int> AcCompanyID { get; set; }
    }
}
