//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTMSV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DR()
        {
            this.DRSExpenses = new HashSet<DRSExpense>();
        }
    
        public int DRSID { get; set; }
        public string DRSNo { get; set; }
        public System.DateTime DRSDate { get; set; }
        public Nullable<int> DeliveredBy { get; set; }
        public int CheckedBy { get; set; }
        public Nullable<decimal> TotalAmountCollected { get; set; }
        public Nullable<int> VehicleID { get; set; }
        public string StatusDRS { get; set; }
        public Nullable<int> AcCompanyID { get; set; }
        public Nullable<bool> StatusInbound { get; set; }
        public string DrsType { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<decimal> TotalMaterialCost { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DRSExpense> DRSExpenses { get; set; }
    }
}
