//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTMSV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriverMaster
    {
        public int DriverID { get; set; }
        public string DriverType { get; set; }
        public string DriverName { get; set; }
        public string NickName { get; set; }
        public string LicenseNo { get; set; }
        public Nullable<System.DateTime> LicenseExpDate { get; set; }
        public string Nationality { get; set; }
        public string PassportNo { get; set; }
        public Nullable<System.DateTime> PassportExpDate { get; set; }
        public string VisaNo { get; set; }
        public Nullable<System.DateTime> VisaExpDate { get; set; }
        public Nullable<int> VehicleTypeID { get; set; }
        public string VehicleNo { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string SponsorName { get; set; }
        public string PhoneNo1 { get; set; }
        public string PhoneNo2 { get; set; }
        public string PhoneNo3 { get; set; }
        public Nullable<int> CountryID4 { get; set; }
        public string PhoneNo4 { get; set; }
        public string LocationName { get; set; }
        public string CityName { get; set; }
        public string CountryName1 { get; set; }
        public string CountryName2 { get; set; }
        public string CountryName3 { get; set; }
    }
}
