//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTMSV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DRR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DRR()
        {
            this.DRRConsignments = new HashSet<DRRConsignment>();
            this.DRRConsignments1 = new HashSet<DRRConsignment>();
            this.DRRInvoices = new HashSet<DRRInvoice>();
            this.DRRInvoices1 = new HashSet<DRRInvoice>();
            this.DRRPKPCADs = new HashSet<DRRPKPCAD>();
            this.DRRPKPCADs1 = new HashSet<DRRPKPCAD>();
            this.DRRRecPays = new HashSet<DRRRecPay>();
            this.DRRRecPays1 = new HashSet<DRRRecPay>();
        }
    
        public int DRRID { get; set; }
        public string DRSNo { get; set; }
        public System.DateTime DRSDate { get; set; }
        public Nullable<System.DateTime> DRRDate { get; set; }
        public Nullable<int> DeliveredBy { get; set; }
        public Nullable<int> CheckedBy { get; set; }
        public decimal TotalAmountCollected { get; set; }
        public Nullable<int> DRSReceiptID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public string StatusDRS { get; set; }
        public Nullable<int> AcJournalID { get; set; }
        public string StatusRunSheet { get; set; }
        public int UserID { get; set; }
        public Nullable<int> FYearID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DRRConsignment> DRRConsignments { get; set; }
        public virtual DRSReceipt DRSReceipt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DRRConsignment> DRRConsignments1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DRRInvoice> DRRInvoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DRRInvoice> DRRInvoices1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DRRPKPCAD> DRRPKPCADs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DRRPKPCAD> DRRPKPCADs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DRRRecPay> DRRRecPays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DRRRecPay> DRRRecPays1 { get; set; }
    }
}
