//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTMSV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DRRConsignment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DRRConsignment()
        {
            this.MCPayments = new HashSet<MCPayment>();
            this.PODs = new HashSet<POD>();
        }
    
        public int DRRConsignmentID { get; set; }
        public int DRRID { get; set; }
        public Nullable<int> InScanID { get; set; }
        public string AWBNO { get; set; }
        public decimal CourierCharge { get; set; }
        public decimal MaterialCost { get; set; }
        public string StatusPaymentMode { get; set; }
        public decimal CCReceived { get; set; }
        public string CCStatuspaymentType { get; set; }
        public string CCBankName { get; set; }
        public string CCChequeNo { get; set; }
        public Nullable<System.DateTime> CCChequeDate { get; set; }
        public string CCRemarks { get; set; }
        public decimal MCReceived { get; set; }
        public string MCStatuspaymentType { get; set; }
        public string MCBankName { get; set; }
        public string MCChequeNo { get; set; }
        public Nullable<System.DateTime> MCChequeDate { get; set; }
        public Nullable<int> OtherAcHeadID { get; set; }
        public string Confirmation { get; set; }
        public string ReceiverName { get; set; }
        public Nullable<System.DateTime> ReceivedTime { get; set; }
        public int CourierStatusID { get; set; }
        public string StatusConsignment { get; set; }
        public Nullable<short> MCPaymentPriority { get; set; }
        public Nullable<bool> StatusSuspenseEntry { get; set; }
    
        public virtual CourierStatu CourierStatu { get; set; }
        public virtual DRR DRR { get; set; }
        public virtual DRR DRR1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MCPayment> MCPayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POD> PODs { get; set; }
    }
}
