//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTMSV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DRRPKPCAD
    {
        public int DRRPKPCADID { get; set; }
        public Nullable<int> DRRID { get; set; }
        public Nullable<int> InScanID { get; set; }
        public string AWBNO { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string StatusPaymentMode { get; set; }
        public string StatusDRRPKPCAD { get; set; }
    
        public virtual DRR DRR { get; set; }
        public virtual DRR DRR1 { get; set; }
    }
}
