//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTMSV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DRSDetail
    {
        public int DRSDetailID { get; set; }
        public int DRSID { get; set; }
        public string AWBNO { get; set; }
        public Nullable<int> InScanID { get; set; }
        public decimal CourierCharge { get; set; }
        public Nullable<decimal> MaterialCost { get; set; }
        public string StatusPaymentMode { get; set; }
        public Nullable<decimal> CCReceived { get; set; }
        public string CCStatuspaymentType { get; set; }
        public string CCBankName { get; set; }
        public string CCChequeNo { get; set; }
        public Nullable<System.DateTime> CCChequeDate { get; set; }
        public Nullable<decimal> MCReceived { get; set; }
        public string MCStatuspaymentType { get; set; }
        public string MCBankName { get; set; }
        public string MCChequeNo { get; set; }
        public Nullable<System.DateTime> MCChequeDate { get; set; }
        public string Remarks { get; set; }
        public string ReceiverName { get; set; }
        public Nullable<System.DateTime> ReceivedTime { get; set; }
        public Nullable<int> CourierStatusID { get; set; }
        public string StatusAWB { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<System.DateTime> ReturnTime { get; set; }
    }
}
