//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTMSV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoldRelease
    {
        public int HoldReleaseid { get; set; }
        public int InScanId { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string Remarks { get; set; }
        public string ActionType { get; set; }
        public int BranchId { get; set; }
    }
}
