//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTMSV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImpExpDocumentMaster
    {
        public int DocumentID { get; set; }
        public string DocumentName { get; set; }
        public string IMPEXPCode { get; set; }
        public Nullable<int> PortID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
    }
}
