//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTMSV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportShipmentDetail
    {
        public int ShipmentDetailID { get; set; }
        public int ImportID { get; set; }
        public string HAWB { get; set; }
        public string AWB { get; set; }
        public int PCS { get; set; }
        public decimal Weight { get; set; }
        public string Contents { get; set; }
        public string Shipper { get; set; }
        public decimal Value { get; set; }
        public string Reciver { get; set; }
        public string DestinationCountry { get; set; }
        public string DestinationCity { get; set; }
        public string BagNo { get; set; }
        public int CurrencyID { get; set; }
        public Nullable<int> ExportShipmentID { get; set; }
        public Nullable<int> QuickInscanID { get; set; }
        public Nullable<int> StatusTypeId { get; set; }
        public Nullable<int> CourierStatusID { get; set; }
    
        public virtual ExportShipment ExportShipment { get; set; }
        public virtual ExportShipment ExportShipment1 { get; set; }
        public virtual ExportShipment ExportShipment2 { get; set; }
        public virtual ImportShipment ImportShipment { get; set; }
    }
}
