//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTMSV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InScanDomestic
    {
        public int InScanDomesticID { get; set; }
        public int InScanID { get; set; }
        public string Refference { get; set; }
        public bool NCND { get; set; }
        public bool CashOnly { get; set; }
        public bool CollectCash { get; set; }
        public bool ChequeOrCash { get; set; }
        public bool DOCopyBack { get; set; }
        public bool CollectMaterial { get; set; }
        public decimal MaterialCost { get; set; }
        public string Remarks { get; set; }
    
        public virtual InScan InScan { get; set; }
    }
}
