//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTMSV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InScantransfer
    {
        public int InScanID { get; set; }
        public string AWBNo { get; set; }
        public System.DateTime InScanDate { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> ConsigneeID { get; set; }
        public Nullable<int> ConsignorID { get; set; }
        public Nullable<int> OriginID { get; set; }
        public Nullable<int> CityID { get; set; }
        public string DestinationID { get; set; }
        public Nullable<int> CustomerRateTypeID { get; set; }
        public string Pieces { get; set; }
        public Nullable<double> StatedWeight { get; set; }
        public Nullable<int> CourierDescriptionID { get; set; }
        public Nullable<int> CourierServiceID { get; set; }
        public Nullable<int> CollectedBy { get; set; }
        public int ReceivedBy { get; set; }
        public decimal CourierCharge { get; set; }
        public Nullable<decimal> OtherCharge { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> CourierStatusID { get; set; }
        public string StatusPaymentMode { get; set; }
        public Nullable<bool> StatusClose { get; set; }
        public string StatusInScan { get; set; }
        public string StatusPickUp { get; set; }
        public Nullable<bool> StatusReconciled { get; set; }
        public Nullable<int> InscanSheetNo { get; set; }
        public bool StatusTransit { get; set; }
        public Nullable<int> TransitID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> EnquiryID { get; set; }
        public Nullable<int> MovementID { get; set; }
        public Nullable<bool> Statuspost { get; set; }
        public Nullable<int> ConsignorCityID { get; set; }
        public Nullable<int> ConsigneeCityID { get; set; }
        public Nullable<int> ExportNo { get; set; }
        public Nullable<int> AcCompanyID { get; set; }
        public Nullable<bool> StatusExport { get; set; }
        public Nullable<System.DateTime> ExportDate { get; set; }
        public Nullable<int> ImportNo { get; set; }
        public Nullable<System.DateTime> ImportDate { get; set; }
        public Nullable<int> AcJournalID { get; set; }
    }
}
