//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTMSV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MCInvoice
    {
        public int MCInvoiceID { get; set; }
        public Nullable<int> McPaymentReceiptID { get; set; }
        public string DocumentNo { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
    }
}
