//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTMSV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MCPayment
    {
        public int MCPaymentID { get; set; }
        public System.DateTime MCPaymentDate { get; set; }
        public string MCPaymentNo { get; set; }
        public int DRRConsignmentID { get; set; }
        public int CustomerID { get; set; }
        public string AWBNo { get; set; }
        public Nullable<decimal> MaterialCost { get; set; }
        public string MCStatuspaymentType { get; set; }
        public string MCBankName { get; set; }
        public string MCChequeNo { get; set; }
        public Nullable<System.DateTime> MCChequeDate { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string Remarks { get; set; }
        public string StatusReturn { get; set; }
        public string DRSNo { get; set; }
    
        public virtual DRRConsignment DRRConsignment { get; set; }
    }
}
