//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTMSV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrepaidAwbDetail
    {
        public int PrepaidAwbDetailID { get; set; }
        public int PrepaidAwbID { get; set; }
        public string AWBNo { get; set; }
        public Nullable<decimal> CourierCharge { get; set; }
        public Nullable<int> InscanID { get; set; }
        public Nullable<bool> statusUpdate { get; set; }
    }
}
