//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTMSV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrepaidAWB
    {
        public int PrepaidAWBID { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> OriginID { get; set; }
        public Nullable<int> DestinationID { get; set; }
        public Nullable<int> NoOfAWBs { get; set; }
        public Nullable<decimal> CourierCharge { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string PaymentMode { get; set; }
        public Nullable<int> AcHeadID { get; set; }
        public string Reference { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string Documentno { get; set; }
        public Nullable<int> AcCompanyID { get; set; }
        public Nullable<int> AcjournalID { get; set; }
    }
}
