//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTMSV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrepaidAWBInvoiceDetail
    {
        public int PrepaidAWBInvoiceDetailID { get; set; }
        public int PrepaidAWBInvoiceID { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public string Destination { get; set; }
        public string AWBNoFrom { get; set; }
        public string AWBNoTo { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<double> MaxAllowedWeight { get; set; }
        public Nullable<int> CountryID { get; set; }
    }
}
