//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTMSV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuickInScanDetail
    {
        public int QuickInscanDetailId { get; set; }
        public Nullable<int> QuickInscanID { get; set; }
        public Nullable<int> InScanId { get; set; }
        public string AWBNo { get; set; }
    }
}
