//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTMSV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RevenueUpdateDetail
    {
        public int ID { get; set; }
        public int MasterID { get; set; }
        public int RevenueCostMasterID { get; set; }
        public decimal Amount { get; set; }
        public bool IsPerfomaInvoice { get; set; }
        public Nullable<decimal> ExpectedAmount { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public Nullable<bool> IsPerfomaCod { get; set; }
        public Nullable<int> AcHeadDebitId { get; set; }
        public Nullable<int> AcHeadCreditId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public Nullable<int> PaymentModeId { get; set; }
        public string InvoiceTo { get; set; }
    
        public virtual RevenueCostMaster RevenueCostMaster { get; set; }
        public virtual RevenueUpdateMaster RevenueUpdateMaster { get; set; }
        public virtual RevenueUpdateMaster RevenueUpdateMaster1 { get; set; }
    }
}
