//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTMSV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAgentCollectionRateDetail
    {
        public int ID { get; set; }
        public int AgentCollectionRateID { get; set; }
        public decimal AdditionalWeightFrom { get; set; }
        public decimal AdditionalWeightTo { get; set; }
        public decimal IncrementalWeight { get; set; }
        public decimal AdditionalRate { get; set; }
    
        public virtual tblAgentCollectionRate tblAgentCollectionRate { get; set; }
    }
}
