//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTMSV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAgentInvoiceDetail
    {
        public int ID { get; set; }
        public Nullable<int> AgentInvoiceID { get; set; }
        public Nullable<int> InscanID { get; set; }
        public Nullable<decimal> CollectedAmount { get; set; }
        public Nullable<decimal> CollectionCharges { get; set; }
        public Nullable<decimal> DeliveryCharges { get; set; }
    
        public virtual tblAgentInvoice tblAgentInvoice { get; set; }
    }
}
