//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTMSV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAgentRecPay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAgentRecPay()
        {
            this.tblAgentRecPayDetails = new HashSet<tblAgentRecPayDetail>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> RecPayDate { get; set; }
        public string VoucherNo { get; set; }
        public Nullable<int> AgentID { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> AcJournalID { get; set; }
        public string StatusRec { get; set; }
        public string StatusOrigin { get; set; }
        public string StatusEntry { get; set; }
        public Nullable<int> FYearID { get; set; }
        public Nullable<int> AcCompanyID { get; set; }
        public string ReferenceNo { get; set; }
        public string Type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAgentRecPayDetail> tblAgentRecPayDetails { get; set; }
    }
}
