//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTMSV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAgentDeliveryRate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAgentDeliveryRate()
        {
            this.tblAgentDeliveryRateDetails = new HashSet<tblAgentDeliveryRateDetail>();
        }
    
        public int ID { get; set; }
        public int AgentID { get; set; }
        public int ZoneChartID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> CourierServiceID { get; set; }
        public decimal BaseWeight { get; set; }
        public decimal BaseRate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAgentDeliveryRateDetail> tblAgentDeliveryRateDetails { get; set; }
    }
}
