//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTMSV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAgentInvoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAgentInvoice()
        {
            this.tblAgentInvoiceDetails = new HashSet<tblAgentInvoiceDetail>();
        }
    
        public int ID { get; set; }
        public string InvoiceNo { get; set; }
        public int AgentID { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public Nullable<decimal> InvoiceTax { get; set; }
        public Nullable<int> AcJournalID { get; set; }
        public bool StatusClose { get; set; }
        public int FYearID { get; set; }
        public Nullable<int> AcCompanyID { get; set; }
        public Nullable<decimal> CollectedAmount { get; set; }
        public Nullable<decimal> CollectionCharges { get; set; }
        public Nullable<decimal> DeliveryCharges { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAgentInvoiceDetail> tblAgentInvoiceDetails { get; set; }
    }
}
