//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTMSV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transit
    {
        public int TransitID { get; set; }
        public int TransitSheetNo { get; set; }
        public System.DateTime TransitDate { get; set; }
        public int EmployeeID { get; set; }
        public int AcCompanyIDOrigin { get; set; }
        public int AcCompanyIDDestination { get; set; }
        public int VehicleID { get; set; }
    }
}
