//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTMSV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleMaster
    {
        public int VehicleID { get; set; }
        public string VehicleDescription { get; set; }
        public string RegistrationNo { get; set; }
        public string Model { get; set; }
        public Nullable<decimal> PurchaseValue { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<System.DateTime> RegExpirydate { get; set; }
        public Nullable<int> VehicleTypeID { get; set; }
        public Nullable<System.DateTime> InsuranceExpDate { get; set; }
        public Nullable<int> AcCompanyID { get; set; }
        public string Mode { get; set; }
        public string FinanceCompany { get; set; }
        public string InsuranceCompName { get; set; }
        public string PolicyNo { get; set; }
        public Nullable<decimal> InsuredValue { get; set; }
        public string Category { get; set; }
        public Nullable<System.DateTime> DepreciationDate { get; set; }
        public Nullable<decimal> ScrapValue { get; set; }
        public Nullable<int> BranchID { get; set; }
        public string MakeYear { get; set; }
        public string RegisteredUnder { get; set; }
    }
}
