//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTMSV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZoneChartDetail
    {
        public int ZoneChartDetailID { get; set; }
        public int ZoneChartID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> CityID { get; set; }
    
        public virtual ZoneChart ZoneChart { get; set; }
        public virtual ZoneChart ZoneChart1 { get; set; }
    }
}
